development:
  adapter: postgresql
  encoding: unicode
  database: leather_development
  pool: 5
  username: postgres
  password: qwerty
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: leather_test
  pool: 5
  username: postgres
  password: qwerty
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: leather_production
  pool: 5
  username: postgres
  password: qwerty
  host: localhost